config/routes.rb
Rails.application.routes.draw do
  
  get 'pages/about'

  devise_for :users
  resources :posts do
    resources :comments
  end
  
  root "posts#index"
  
  match ':controller(/:action(/:id))', :via=> [:get, :post]
  get 'categories/index'

  get 'categories/show'

end

app/models/category.rb
class Category < ActiveRecord::Base
    
    has_many :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    
      belongs_to :post
      belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
    
    validates_presence_of :title
    validates_presence_of :category
    validates_presence_of :body
    
    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }#, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
    
    has_many :comments
    belongs_to :category
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
         validates_presence_of :user_name
         
     has_many :posts    
     has_many :comments
     
      has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
      validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

 
     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
    before_action :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  


 protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:user_name, :email, :password, :password_confirmation, :remember_me, :avatar) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :user_name, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:user_name, :email, :password, :password_confirmation, :current_password, :avatar) }
  end
  
   
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def index
    @category = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @title = @category.title
    @post = @category.posts
  end
  
  def new
    redirect_to(:controller => "posts", :action => "new")
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
    def create
        params.permit!
        @post = Post.find(params[:post_id])
        @comment = @post.comments.build(params[:comment])
        @comment.user_id = current_user.id if current_user || nil
        @comment.save
        redirect_to post_path(@post)
    end
    
    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id]).destroy
        redirect_to post_path(@post)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :category]
  
  def index
    @posts = Post.all.order("created_at DESC")
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = current_user.posts.build
    @cat = Category.all
  end
  
  def create
    params.permit!
    @post = current_user.posts.build(post_params)
    
    if (@post).save
      flash[:notice] = "Post created successfully."
       redirect_to @post
    else
       render('new')
    end
  end

  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      flash[:notice] = "Post updated successfully."
        redirect_to @post
    else
        render('edit')
    end
  end

  def delete
     @post = Post.find(params[:id])
  end
  
  def destroy
     post = Post.find(params[:id]).destroy
     flash[:notice] = "Post '#{post.title}' destroyed successfully."
     redirect_to(:action => "index")
  end
  
  private
        
    def post_params
        params.require(:post).permit(:title, :body, :category_id, :image, :avatar)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    

end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def markdown(text)
      options = {
      filter_html:     true,
      hard_wrap:       true, 
      no_styles: true,
      space_after_headers: true, 
      prettify:true
    }

      extensions = {
      autolink:           true,
      no_intra_emphasis: true,
      highlight: true,
      gh_blockcode: true,
      quote: true,
      fenced_code_blocks: true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

        renderer = Redcarpet::Render::HTML.new(options)
        markdown = Redcarpet::Markdown.new(renderer, extensions)
        
        markdown.render(text).html_safe
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
 module DeviseHelper
  
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
                        count: resource.errors.count,
                        resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
      <h2>#{sentence}</h2>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end
 end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<h1>Categories</h1>
<% @category.each do |cat|%>
    <ul>
        <li> <%= link_to cat.title, {:action => 'show', :id => cat.id} %> </li>
    </ul>
<%end%>

app/views/categories/show.html.erb
<article class = "lleft">
<h1><%= @category.title %></h1>

<% @post.each do |post|%>

     <p><span class = "post-title"><%= link_to post.title, post%></span></p>


     <% if post.image.file? %>
          <p><%= image_tag post.image.url(:thumb), :class => "img-fl" %></p>
     <%end%>
 
     <p class = "postts"><%= markdown(post.body) %></p><br/> <hr/>

<%end%> 
</article>

app/views/comments/_comment.html.erb
<div class = "cmm">
    
<% @post.comments.each do |comment| %>
    <p class="comment_name">Name :<strong><%= (comment.user.user_name if comment.user) || "Anonymous" %></strong></p>
    <p class="comment_body"><%= comment.body %></p>
    <p class="comment_time"><small><em><%= time_ago_in_words(comment.created_at) %> Ago</em></small></p>
    <p><%= link_to 'Delete', [comment.post, comment],
                    method: :delete, data: {confirm: 'Are you sure?'}, :class => "ln ree" %></p>    
    <hr/>
    
<%end%>

</div>

app/views/comments/_form.html.erb
<div class = "comment">

    <%= form_for [@post, @post.comments.build] do |f| %>
    
        
        <%= f.label :body, "Comment:" %><br>
        <%= f.text_area(:body, :size => "40x5")%><br/>
        <br/>
        <%=submit_tag("submit")%>
    <%end%>
       
    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<meta name="viewport" content="width=device-width, initial-scale=1">
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application','https://fonts.googleapis.com/css?family=Oleo+Script' %>
  <%= stylesheet_link_tag 'application','https://fonts.googleapis.com/css?family=Iceberg' %>
  <%= stylesheet_link_tag 'application','https://fonts.googleapis.com/css?family=Roboto' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrapper">
   <header>
   	
		<%if user_signed_in?%>
			<div class="signed-in"><em>Signed in as
				<%if current_user.avatar?%>
				<div class = "round">
					<%= image_tag(current_user.avatar.url(:thumb), :class => 'imagee') %>--</em>
				</div>
				<%else%>
					<%=current_user.user_name%>
				<%end%>
			</div> 
		<%end%>
	
	<h2><span class = "head">Blogy</span></h2>
	<nav class = "right">
		<ul>
			<li><%= link_to "New Post", {:action => 'new'}, class: "links", :class => "ln darb" %> </li>
		<% if user_signed_in? %>
			<li><%= link_to "Sign Out",destroy_user_session_path, method: :delete, class: "links", :class => "ln darb" %></li>
		<%else%>
			<li><%= link_to "Sign in",new_user_session_path, class: "links", :class => "ln darb" %> </li>
			<li><%= link_to "Sign Up" ,new_user_registration_path, class: "links", :class => "ln darb" %></li>
		<%end%>
		</ul>	
	</nav>
	<nav id = "left">
	<ul>
	    <li><%= link_to "Posts", posts_path, class: "links", :class => "ln darb" %> </li>
		<li><%= link_to "Categories", categories_index_path, class: "links", :class => "ln darb" %> </li>
	   	<li><%= link_to "About", pages_about_path, class: "links", :class => "ln darb" %></li>
	  </ul>
	</nav>
	</header>
<section class = "right">
	<article class= "category">
	  <h3><em><span class = "rf">C</span>ategories</em></h3>
	  <div class ="tete">
		  <ul class ="none">
			 <li><%= link_to("Electronics", {:controller => 'categories', :action => 'show', :id => 2}, :class => "ln categ")%></li>
			 <li><%= link_to("Networking", {:controller => 'categories', :action => 'show', :id => 3}, :class => "ln categ")%></li>
		     <li><%= link_to("Programming", {:controller => 'categories', :action => 'show', :id => 1}, :class => "ln categ")%></li>
		  </ul>
	  </div>
	</article>
</section>
	
<% if notice %>
	<div class = "not">
	  <p class = "notice"><%= notice %></p>
	</div>
<%elsif alert%>
      <p class = "alert"><%= alert %></p>
<%end%> 
  
<section class = "left">
	<%= yield %>
</section>

  <footer>
		<p>A simple Rails Blog app from <strong>ViKraM.</strong></p>
	</footer>

</div>

</body>
</html>

app/views/pages/about.html.erb
<article class = "about">
 <h1>About</h1>
 
 <p id = "ind"><span class = "rf">I</span> make websites using Ruby on Rails.   After I finished my college, 
 I had a great passion towards Coding.I learnt a Simple and Powerful Programming language Ruby and some web 
 developing languages. I had a great fun while learning it :) This is my first website, and I feel awsome that
 my website comes online. Also I am fasinated in creating more websites. Hope I will see you again with some
 updates and new websites :)</p>

</article>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
	<div class="errors">
	<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
	   	<ul>
			<% @post.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>



    <%= f.label(:title) %><br>
    
    <%= f.text_field(:title, :size => "40x0", :class => 'postts') %><br> 
    <br>
    
    <%= f.label(:image) %><br>
    
    <%= f.file_field(:image) %><small>(optional)</small><br> 
    <br>
    
    <%= f.label(:category_id, "Category") %><br/>
    
    
    <%= f.collection_select :category_id, Category.all, :id, :title, :prompt => 'Select One' %>
   </br>
    
    
    
    <br/>
    
    <%= f.label(:body) %><br>
    
    <%= f.text_area(:body, :size => "80x12", :class => 'postts') %><br>
    <br>

	

app/views/posts/edit.html.erb
<div class="lleft">
    
	<h1>Edit Post</h1>
	
	<%= form_for(@post, :url => {:controller => 'posts', :action => 'update'}, html: { multipart: true }) do |f| %>
	
		<%= render(:partial => "form", :locals => {:f => f}) %>
	

		<%= submit_tag("Update Subject") %>
	
	<% end %>
	
</div>  

app/views/posts/index.html.erb
<article class = "lleft">
    
    
   <h1><span class = "p">P</span>osts</h1> 
    
    <% @posts.each do |post| %>
    
    <div>
    <%= link_to(:action => 'show', :id => post) do %>
        <span  class = "lin"><i><span class = "post-title"><%= post.title.capitalize %></i></span>
        <small>--Posted By--</small><span class = "post-username"><b><span id = "usertrans"><%= post.user.user_name %>.</span></b></span></span>
    </div>
    <% end %>
        <div class = "imagee">
        <% if post.image.file? %>
            <p class = 'imgee'><%= image_tag post.image.url(:thumb),:class => "img-fl" %></p>
        <%end%>
           <p class = "postts"><%= (truncate post.body, length: 460) %>
           <%= link_to 'Read more', post %> </p> <hr/></div>
           
           
    <% end %>
    
</article>

app/views/posts/new.html.erb
<div id="new-pos">
	
	<h1>New Post</h1>
	
	<%= form_for(:post, :url => {:action => 'create'}, html: { multipart: true }) do |f| %>
	
		<%= render(:partial => "form", :locals => {:f => f}) %>
		
		<%= submit_tag("Create Post") %>
		
	<% end %>
	
</div>

app/views/posts/show.html.erb
<article class = "lleft">
<div class ="pos-pad">
   <span class = "post-title"><%= @post.title %></span> <small><%= @post.created_at.strftime("%b %d, %Y") %> </small>
   <p><small>Category : <strong><%=@post.category.title %></strong></small></p>
    <%if @post.image.file? %>
        <%= image_tag @post.image.url(:medium), :class => "img-sh" %>
    <%end%>
    <div class = "postts">
        <p><%= markdown(@post.body)%></p>
    </div>
            
    <%if user_signed_in? %>
        <%if @post.user == current_user %>
             <%= link_to 'Edit', edit_post_path(@post), :class => "ln lgr" %> |
             <%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: 'Are you sure?'}, :class => "ln ree" %>
        <%end%>
    <%end%>
</div><br/>

<hr/>
    <div class ="cs">
        <h4><%= @post.comments.count %> Comments</h4>
		<%= render partial: "comments/comment" %>
    </div>
    
    <div class = "comment">
        <p><strong>Add a Comment</strong></p>
        <%= render partial: "comments/form" %>
    </div>
    
</article>